name: Build QMK firmware
on:
  - push
  - pull_request
  - workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    name: QMK Userspace Build
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
      preparation_command: mkdir qmk_firmware/keyboards/cosmos && cp -r keyboards/* qmk_firmware/keyboards/cosmos/ && qmk userspace-doctor
  publish:
    name: QMK Userspace Publish
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build
